data:
  dataset_name: "sartajbhuvaji/brain-tumor-classification-mri"
  input_size: 224
  batch_size: 64
  num_workers: 2

model:
  arch: resnet18
  num_classes: 4
  pretrained: true

training:
  epochs: 20
  lr: 0.0001
  weight_decay : 0.002
  save_path: "checkpoints/best-model-checkpoint.pt"

